{"name": "test_login_failed_user_password_wrong[case1]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': 'aaa', 'password': 'qqqqqqqq', 'check': '用户名不符合规则'}"}], "start": 1665209569508, "stop": 1665209570476, "uuid": "90a238ef-e121-4305-8026-66b006db9465", "historyId": "fe43b59c65e6526b91fb37ac9c7d3788", "testCaseId": "253d57a3ffef1d7866e3686ffe2eb276", "fullName": "TestCases.test_login.TestLogin#test_login_failed_user_password_wrong", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init', 'back_to_login_page')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-E380NSU"}, {"name": "thread", "value": "18584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}