{"name": "test_login_failed_user_password_wrong[case2]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'password': 'qqqqqqqq', 'check': '用户名不符合规则'}"}], "start": 1665209570546, "stop": 1665209571084, "uuid": "9ec31062-1703-4b71-b3cf-e9811e65cdf5", "historyId": "d837cdd4a815225c3b2dface1fe13368", "testCaseId": "253d57a3ffef1d7866e3686ffe2eb276", "fullName": "TestCases.test_login.TestLogin#test_login_failed_user_password_wrong", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init', 'back_to_login_page')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-E380NSU"}, {"name": "thread", "value": "18584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}